"""journals

Revision ID: 0168cd9fb79d
Revises: 2668672ddbec
Create Date: 2025-10-27 21:18:35.954198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0168cd9fb79d'
down_revision = '2668672ddbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'moods', ['mood_id'], ['id'])
        batch_op.drop_column('mood')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mood_id')

    # ### end Alembic commands ###
